### ISSUE TITLE
Pan with two fingers

### ISSUE THREAD

**Issue by Vic0429** [fljot/Gestouch#34]
Hi
I have an image which can be transformed (pan and zoom) while the user can draw on it with one finger (longPressGesture). So i want to draw with one finger and pan with two fingers. How can i set the the pan gesture to require two touches?

**Comment by fljot** [comment]
Your IDE's autocompletion should kindly give you hints for `maxNumTouchesRequired` and `minNumTouchesRequired` properties. Setting both to 2 should do the trick.
But wait, are you using PanGesture and ZoomGesture to transform or TransformGesture? I would recommend you to use TransformGesture just because it's easier to deal with a single gesture instance other than two. In this case you can do not do anything in handler when `gesture.touchesCount < 2` (when single touch panning).

And why (and how) do you draw with LongPressGesture?

**Comment by Vic0429** [comment]
Thanks, it worked...

I use TransformGesture

I want use another gesture instead of LongPressGesture but I don't know which one should I use...

Here's the code for drawing:

var drawTouch:LongPressGesture = new LongPressGesture(stage)
drawTouch.minPressDuration = 0
drawTouch.numTouchesRequired = 1
drawTouch.addEventListener(GestureEvent.GESTURE_BEGAN, startDrawing)
drawTouch.addEventListener(GestureEvent.GESTURE_CHANGED, drawIt)
drawTouch.addEventListener(GestureEvent.GESTURE_ENDED, stopDrawing)

public function startDrawing(e:GestureEvent):void
{
    drawingBoard.graphics.moveTo(drawTouch.location.x, drawTouch.location.y);
    drawing = true;
}

public function drawIt(e:GestureEvent)
{
    if(drawing)
    {
        drawingBoard.graphics.lineTo(drawTouch.location.x, drawTouch.location.y);
    }
}

public function stopDrawing(e:GestureEvent)
{
    drawing = false;
}

I know that it's not the best way to draw with touch but it was originally designed for MouseEvents...

I have another problem with the LongPressGesture. If I don't touch the screen then slide my finger (to draw), but touch it while moving my finger, the gesture fails.

**Comment by fljot** [comment]
Well unfortunately Gestouch does not help you with raw touches (yet?), which could be good for things like your drawing.
Does LongPressGesture actually work well together with TransformGesture in this case? Because as I can imagine due to `minPressDuration = 0` it should recognize immediately on touch therefore causing TransformGesture to fail.
Anyhow, I would do it at least with PanGesture (min & maxNumTouchesRequired = 1). And the key moment here is recognition upon first touch.
So you touch first — both gestures receive touch, but both are still in POSSIBLE state.
You move your finger a bit (`slop` distance) — both gestures are about to be recognized. But since you don't want TransformGesture to be recognized in this case (or what's more important you don't want TransformGesture recognition to cause PanGesture failure!) you must set `delegate` and focus on `gestureShouldBegin(gesture:Gesture):Boolean` method which should look something like:

```
transformGesture.delegate = this;//this must implement IGestureDelegate
public function gestureShouldBegin(gesture:Gesture):Boolean
{
    if (panGesture.state == GestureState.POSSIBLE && panGesture.touchesCount > 0)
        return false;//pan is probably about to be recognized, give it a chance
    return true;//default behavior
}
```

This way whenever you move with single finger you can be sure that Pan will be recognized, not Transform.
And if you place two fingers — pan (which requires strictly one touch) will fail and Transform will be later (once you actually move) recognized. Clear?

I didn't get your last question. Explain again please.

**Comment by Vic0429** [comment]
Thanks again for your answer,
I'll try it...
I think in this case my last question is no longer relevant.

**Comment by fljot** [comment]
@Vic0429 any more questions on this?

**Comment by Vic0429** [comment]
No.
It's working perfectly now...
