### ISSUE TITLE
Trouble Changing Input Modes

### ISSUE THREAD

**Issue by kitschpatrol** [fljot/Gestouch#4]
Is this the correct way to change input mode from mouse to touch?

GesturesManager.initDefaultInputAdapter = false;
GesturesManager.getInstance().addInputAdapter(new TouchInputAdapter(this.stage));

**Comment by fljot** [comment]
Yes. But important to do this ASAP, before library initialized default one. What's the trouble, it doesn't work for you?

Normally you don't need to do this, since library initializes appropriate one (Mouse.. or Touch..) based on Multitouch.supportsTouchEvents. You might like to do this to enabled BOTH Mouse and Touch input adapters (in case you develop on multitouch screen + mouse.. I recently got info that it doesn't really work as expected, but I'll fix it and it will be possible to do so).

**Comment by fljot** [comment]
@kitschpatrol so have you managed?

**Comment by kitschpatrol** [comment]
Thanks @fljot! Yes I think the reason I had to specify the input mode manually is because I'm trying to use Gestouch with an MacBook trackpad / Magic Trackpad via [TrackPadConnector](https://github.com/kitschpatrol/TrackPadConnector), which doesn't trip the native Multitouch.supportsTouchEvents boolean.

It seems to work for tapping gestures but not dragging / zooming / etc... I don't have time to troubleshoot at the moment but would be interested in getting TrackPadConnector working with Gestouch.
