### ISSUE TITLE
Multiple Tap Listeners Programmatically

### ISSUE THREAD

**Issue by brycebigger** [fljot/Gestouch#58]
First off, let me say that Gestouch is amazing, works well in Flash, but even better, works well with Scaleform! In doing some FUI interfaces, it has been so easy to test and iterate. It's tough to do quick testing on iOS no matter what- the build/deploy process takes about a minute every time, so that adds up. Testing touch interfaces immediately with a touch monitor is super quick, but typically the cheap ones on have two simultaneous touch points, but I digress.

Here's my issue: I'm building a horizontal, scrolling menu that's populated with the same MovieClip, about 20 of them, so the movieclip container ends up being about 3000px wide. Enter a swipe gesture to make them go back and forth. Done. Now, to select an individual movieclip and get it's id, name, etc. is where I'm slipping up.

Here's my code:

for (var i:int = 0; i < numberOfNodesToAdd; i++) {
var menuItem:MenuItem = new MenuItem();
/\* skipping a bunch of formatting stuff */
var singleTap:TapGesture = new TapGesture(menuItem);
singleTap.numTapsRequired = 1;
singleTap.addEventListener(TapGestureEvent.GESTURE_TAP, menuItemTap);

//more code and then finally, container.addChild(menuItem);

}

private function menuItemTap(e:TapGestureEvent):void
{
//The line below doesn't work, but I'm not sure how to target it exactly...
//TweenMax.to(e.currentTarget.bg, 1, {tint:0xff0000});

trace(e.currentTarget);  //returns object
}

This is a project I'm using the Flash IDE (CS6 and CC). Any thoughts/insight on how to figure out what I pressed? I'm sure I'm missing something simple...

Thanks!
Bryce

**Comment by fljot** [comment]
Well first of all, have you simply tried to understand what event.currentTarget is? This property is related to the concept of bubbling events. There is no event bubbling in gestures, why would you use that. Anyhow, it should be equal to event.target which is obviously the gesture itself since it has dispatched the event. And your sprite is the `gesture.target` (or `(event.target as Gesture).target`).

Second thing is that it's a bit expensive to register so many gestures. You could have several gesture instances and change their `target` property depending on which items are actually visible on the screen at the moment. Another option is to have just one gesture on the container, and in gesture handler use some hittest to find the object under `gesture.location`.

And finally (the thing I say a lot) — DON'T USE SWIPE GESTURE FOR GALLERIES. It's sort of hidden and a bit tricky to use. Look at your smartphone again — all galleries are continuously track your touch and move pictures. Use PanGesture.
