### ISSUE TITLE
TransformGesture on container with children using PanGesture

### ISSUE THREAD

**Issue by dejv** [fljot/Gestouch#66]
Hi!

I got a container with a dynamic number of children sprites. Each child uses a PanGesture to allow the user to move it around within the container.

I would like to invoke a TransFormGesture on the container so that I can zoom and pan it (pan using two fingers). I have a setup currently with a TransformGesture on the stage. My problem is naturally that if the user wants to zoom or pan, and sets down their first finger onto one of the child objects, that child's PanGesture starts. With my current setup the user would have to aim in between the children to successfully start the TransformGesture

I'd love it if anyone could enlighten me as to what would be a good strategy for solving this? Slop on the PanGesture? Is it wrong to use a PanGesture like I do? Something more elegant?

**Comment by fljot** [comment]
Well I'd call it not the best UI design in the first place. That's why you encounter this problem.
I can suggest you a technical solution, so you decide yourself what you do after all.

Option one: you use just single TransformGesture (on container). When gesture begins you check how many touches it tracks (`transformGesture.touchesCount`). If it's == 1 and you're not in the space between children, you mark somewhere that you're performing child panning and find the appropriate child using `transformGesture.location` or by extending gesture and getting information out of `touch.target`. If touchesCount == 2 on GESTURE_BEGAN you do container stuff.

Option two: extend TransformGesture and override (assuming you're using flash.display.*)

```
private var childPanGesturesMap:Dictionary = new Dictionary();
override public function reset():void
{
    super.reset();
    childPanGesturesMap = new Dictionary();//or remove elements
}

override gestouch_internal function canBePreventedByGesture(preventingGesture:Gesture):Boolean
{
    if (preventingGesture is PanGesture && (this.target as DisplayObjectContainer).contains(preventingGesture.target as DisplayObject)
    {
        // this way we save references to child pan gestures, so later we can later stop (abort) them manually
        childPanGesturesMap[preventingGesture] = true;
        return false;//pan gestures won't abort transform gesture recognition)
    }
    return true;
}

override protected function setState(newState:GestureState):Boolean
{
    // prevent early recognition, as you say you're interested only in 2-fingers transformation
    if (newState == GestureState.BEGAN)
    {
        if (touchesCount < 2)
            return false;// I should probably add numTouchesRequired property so TransformGesture could be more configurable!
        //else
        var result:Boolean = super.setState(newState);
        if (result)
        {
            for (var g:* in childPanGesturesMap)
            {
                (g as Gesture).reset();
            }
        }
        return result;
    }

    return super.setState(newState);
}
```

Ask if something is not clear enough, as you'd better understand what happens just one pixel under the hood. And obviously, I haven't tested this! =)

**Comment by dejv** [comment]
Thank you fljot for your excellent answer, got option 1 working perfectly. It also saved me a ton of listeners! 

My hats off to you.
Thanks
